(define (domain egocentric-video)
    (:requirements :strips :typing :negative-preconditions)

    (:types
        object hand recipient - object
        tool - object
    )

    (:predicates
        (above ?x ?y)
        (attached-to ?x ?y)
        (broken ?x)
        (can-dry ?y)
        (can-fit ?x ?y)
        (cut ?x)
        (deformed ?x)
        (flipped ?x)
        (folded ?x)
        (in ?x ?y)
        (is-equal ?x ?y)
        (in-hand ?x)
        (is-active ?x)
        (is-attached ?x)
        (is-breakable ?x)
        (is-clean ?x)
        (is-container ?x)
        (is-cuttable ?x)
        (is-deformable ?x)
        (is-empty ?x)
        (is-flippable ?x)
        (is-fluid ?x)
        (is-foldable ?x)
        (is-holdable ?x)
        (is-mixable ?x)
        (is-movable ?x)
        (is-openable ?x)
        (is-peelable ?x)
        (is-pourable ?x)
        (is-scoopable ?x)
        (is-shakeable ?x)
        (is-solid ?x)
        (is-tearable ?x)
        (is-waste ?x)
        (mixed ?x)
        (on ?x ?y)
        (onsurface ?x)
        (opened ?x)
        (peeled ?x)
        (shaken ?x)
        (stretched ?x)
        (torn ?x)
        (touching ?x ?y)
        (touching-hand ?x)
        (wet ?x)
        (within-reach ?x)
    )
    (:action put
        :parameters (?x)
        :precondition (and
            (in-hand ?x)
            (touching-hand ?x)
            (not (onsurface ?x))
            (is-holdable ?x)
            (within-reach ?x)
        )
        :effect (and
            (not (in-hand ?x))
            (onsurface ?x)
            (not (touching-hand ?x))
            (is-holdable ?x)
            (within-reach ?x)
        )
    )
    (:action take
        :parameters (?x ?y)
        :precondition (and
            (not (in-hand ?x))
            (not (in-hand ?y))
            (is-holdable ?x)
            (is-holdable ?y)
            (within-reach ?x)
            (within-reach ?y)
            (onsurface ?x)
            (onsurface ?y)
            (not (touching-hand ?x))
            (not (touching ?y hand))
        )
        :effect (and
            (in-hand ?x)
            (in-hand ?y)
            (not (onsurface ?x))
            (not (onsurface ?y))
            (is-holdable ?x)
            (is-holdable ?y)
            (within-reach ?x)
            (within-reach ?y)
            (touching-hand ?x)
            (touching ?y hand)
        )
    )
    (:action open
        :parameters (?x)
        :precondition (and
            (is-openable ?x)
            (within-reach ?x)
            (touching-hand ?x)
            (not (opened ?x))
        )
        :effect (and
            (is-openable ?x)
            (within-reach ?x)
            (not (touching-hand ?x))
            (opened ?x)
        )
    )
    (:action close
        :parameters (?x)
        :precondition (and
            (is-openable ?x)
            (within-reach ?x)
            (touching-hand ?x)
            (opened ?x)
        )
        :effect (and
            (is-openable ?x)
            (within-reach ?x)
            (not (touching-hand ?x))
            (not (opened ?x))
        )
    )
    (:action pour
        :parameters (?x ?y)
        :precondition (and
            (above ?x ?y)
            (not (full ?y))
            (is-container ?y)
            (is-pourable ?x)
            (within-reach ?x)
            (in-hand ?x)
        )
        :effect (and
            (not (is-equal ?x ?y))
            (not (above ?x ?y))
            (not (full ?y))
            (is-container ?y)
            (is-pourable ?x)
            (within-reach ?x)
            (in ?x ?y)
            (not (in-hand ?x))
        )
    )
    (:action fold
        :parameters (?x)
        :precondition (and
            (is-foldable ?x)
            (not (is-rigid ?x))
            (not (folded ?x))
            (within-reach ?x)
            (touching-hand ?x)
            (in-hand ?x)
        )
        :effect (and
            (is-foldable ?x)
            (not (is-rigid ?x))
            (folded ?x)
            (within-reach ?x)
            (touching-hand ?x)
            (in-hand ?x)
        )

    )
    (:action rip
        :parameters (?x)
        :precondition (and
            (is-tearable ?x)
            (within-reach ?x)
            (not (torn ?x))
            (in-hand ?x)
            (touching-hand ?x)
        )
        :effect (and
            (torn ?x)
            (is-tearable ?x)
            (in-hand ?x)
            (touching-hand ?x)
        )
    )
    (:action insert
        :parameters (?x ?y)
        :precondition (and
            (not (on ?x ?y))
            (is-holdable ?x)
            (touching-hand ?x)
            (within-reach ?x)
            (within-reach ?y)
            (not (closed ?y))
            (not (full ?y))
            (can-fit ?x ?y)
        )
        :effect (and
            (on ?x ?y)
            (is-holdable ?x)
            (not (touching-hand ?x))
            (within-reach ?x)
            (within-reach ?y)
        )
    )
    (:action move
        :parameters (?x ?y)
        :precondition (and
            (is-movable ?x)
            (touching-hand ?x)
            (within-reach ?x)
            (within-reach ?y)
            (is-container ?y)
            (not (in ?x ?y))
        )
        :effect (and
            (is-movable ?x)
            (not (touching-hand ?x))
            (within-reach ?x)
            (within-reach ?y)
            (is-container ?y)
            (in ?x ?y)
        )
    )
    (:action throw
        :parameters (?x ?y)
        :precondition (and
            (in-hand ?x)
            (is-container ?y)
            (within-reach ?x)
            (within-reach ?y)
            (not (full ?y))
            (is-waste ?x)
        )
        :effect (and
            (not (in-hand ?x))
            (is-container ?y)
            (within-reach ?x)
            (within-reach ?y)
            (is-waste ?x)
        )
    )
    (:action dry
        :parameters (?x ?y)
        :precondition (and
            (wet ?x)
            (within-reach ?x)
            (within-reach ?y)
            (in-hand ?y)
            (can-dry ?y)
        )
        :effect (and
            (not (wet ?x))
            (within-reach ?x)
            (within-reach ?y)
            (in-hand ?y)
            (can-dry ?y)
        )
    )
    (:action shake
        :parameters (?x)
        :precondition (and
            (is-shakeable ?x)
            (not (shaken ?x))
            (within-reach ?x)
            (in-hand ?x)
        )
        :effect (and
            (shaken ?x)
            (within-reach ?x)
            (in-hand ?x)
        )
    )
    (:action empty
        :parameters (?x ?y)
        :precondition (and
            (not (is-empty ?x))
            (in-hand ?x)
            (within-reach ?x)
            (within-reach ?y)
            (not (full ?y))
            (is-container ?y)
            (not (in ?x ?y))
        )
        :effect (and
            (is-empty ?x)
            (not (is-empty ?y))
            (is-container ?y)
            (within-reach ?x)
            (within-reach ?y)
            (in ?x ?y)
        )
    )
    (:action turn-on
        :parameters (?x)
        :precondition (and
            (not (is-active ?x))
            (within-reach ?x)
        )
        :effect (and
            (is-active ?x)
            (within-reach ?x)
        )
    )
    (:action turn-off
        :parameters (?x)
        :precondition (and
            (is-active ?x)
            (within-reach ?x)
        )
        :effect (and
            (not (is-active ?x))
            (within-reach ?x)
        )
    )
    (:action squeeze
        :parameters (?x)
        :precondition (and
            (is-deformable ?x)
            (not (deformed ?x))
            (within-reach ?x)
            (in-hand ?x)
        )
        :effect (and
            (is-deformable ?x)
            (deformed ?x)
            (within-reach ?x)
            (in-hand ?x)
        )
    )
    (:action mix
        :parameters (?x ?y)
        :precondition (and
            (is-mixable ?x)
            (not (mixed ?x))
            (in-hand ?y)
            (within-reach ?x)
        )
        :effect (and
            (is-mixable ?x)
            (mixed ?x)
            (in-hand ?y)
            (within-reach ?x)
        )
    )
    (:action scoop
        :parameters (?x ?tool)
        :precondition (and
            (is-scoopable ?x)
            (within-reach ?x)
            (in-hand ?y)
            (is-empty ?y)
            (not (in ?y ?x))
        )
        :effect (and
            (not (is-empty ?y))
            (within-reach ?x)
            (in-hand ?y)
            (in ?y ?x)
        )
    )
    (:action peel
        :parameters (?x)
        :precondition (and
            (is-peelable ?x)
            (not (peeled ?x))
            (within-reach ?x)
            (in-hand ?x)
        )
        :effect (and
            (peeled ?x)
            (not (is-peelable ?x))
            (within-reach ?x)
            (in-hand ?x)
        )
    )
    (:action apply
        :parameters (?x ?y)
        :precondition (and
            (not (on ?x ?y))
            (is-fluid ?x)
            (within-reach ?x)
            (within-reach ?y)
            (not (full ?y))
            (is-solid ?y)
        )
        :effect (and
            (on ?x ?y)
            (is-fluid ?x)
            (not (is-empty ?y))
            (is-solid ?y)
            (within-reach ?x)
            (within-reach ?y)
        )
    )
    (:action press
        :parameters (?x)
        :precondition (and
            (is-deformable ?x)
            (not (deformed ?x))
            (within-reach ?x)
            (touching-hand ?x)
        )
        :effect (and
            (is-deformable ?x)
            (deformed ?x)
            (within-reach ?x)
            (not (touching-hand ?x))
        )
    )
    (:action cut
        :parameters (?x)
        :precondition (and
            (is-cuttable ?x)
            (within-reach ?x)
            (not (cut ?x))
        )
        :effect (and
            (is-cuttable ?x)
            (within-reach ?x)
            (cut ?x)
        )
    )
    (:action flip
        :parameters (?x)
        :precondition (and
            (is-flippable ?x)
            (within-reach ?x)
            (not (flipped ?x))
        )
        :effect (and
            (is-flippable ?x)
            (within-reach ?x)
            (flipped ?x)
        )
    )
    (:action break
        :parameters (?x)
        :precondition (and
            (is-breakable ?x)
            (within-reach ?x)
            (not (broken ?x))
            (in-hand ?x)
            (touching-hand ?x)
        )
        :effect (and
            (broken ?x)
            (not (is-breakable ?x))
            (in-hand ?x)
            (touching-hand ?x)
        )
    )
    (:action fill
        :parameters (?x ?y)
        :precondition (and
            (not (full ?x))
            (is-container ?x)
            (is-fluid ?y)
            (within-reach ?x)
            (not (in ?y ?x))
        )
        :effect (and
            (not (is-empty ?x))
            (is-container ?x)
            (is-fluid ?y)
            (within-reach ?x)
            (in ?y ?x)
        )
    )
    (:action hold
        :parameters (?x)
        :precondition (and
            (touching-hand ?x)
            (within-reach ?x)
            (onsurface ?x)
        )
        :effect (and
            (touching-hand ?x)
            (within-reach ?x)
            (onsurface ?x)
        )
    )
    (:action stretch
        :parameters (?x)
        :precondition (and
            (is-deformable ?x)
            (not (stretched ?x))
            (within-reach ?x)
            (in-hand ?x)
        )
        :effect (and
            (is-deformable ?x)
            (stretched ?x)
            (within-reach ?x)
            (in-hand ?x)
        )
    )
    (:action attach
        :parameters (?x ?y)
        :precondition (and
            (not (is-attached ?x))
            (not (attached-to ?x ?y))
            (within-reach ?x)
            (within-reach ?y)
            (in-hand ?x)
        )
        :effect (and
            (is-attached ?x)
            (attached-to ?x ?y)
            (within-reach ?x)
            (within-reach ?y)
            (not (in-hand ?x))
        )
    )
    (:action add
        :parameters (?x ?y)
        :precondition (and
            (not (on ?x ?y))
            (within-reach ?x)
            (within-reach ?y)
            (not (full ?y))
            (can-fit ?x ?y)
        )
        :effect (and
            (on ?x ?y)
            (within-reach ?x)
            (within-reach ?y)
        )
    )
    (:action wash
        :parameters (?x)
        :precondition (and
            (not (wet ?x))
            (within-reach ?x)
            (in-hand ?x)
            (not (is-clean ?x))
        )
        :effect (and
            (wet ?x)
            (within-reach ?x)
            (in-hand ?x)
            (is-clean ?x)
        )
    )
    (:action remove
        :parameters (?x ?y)
        :precondition (and
            (on ?x ?y)
            (within-reach ?x)
            (within-reach ?y)
            (not (touching-hand ?x))
        )
        :effect (and
            (not (on ?x ?y))
            (within-reach ?x)
            (within-reach ?y)
            (touching-hand ?x)
        )
    )
    (:action scrape
        :parameters (?x ?y)
        :precondition (and
            (is-attached ?x)
            (within-reach ?x)
            (within-reach ?y)
            (in-hand ?y)
        )
        :effect (and
            (not (is-attached ?x))
            (within-reach ?x)
            (within-reach ?y)
            (in-hand ?y)
        )
    )
    (:action pat
        :parameters (?x ?y)
        :precondition (and
            (not (touching ?x ?y))
            (within-reach ?x)
            (within-reach ?y)
            (in-hand ?x)
        )
        :effect (and
            (touching ?x ?y)
            (within-reach ?x)
            (within-reach ?y)
            (in-hand ?x)
        )
    )
)
