TRAIN:
  ENABLE: True
  DATASET: EpicKitchensGRU
  BATCH_SIZE: 1
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: weights/SLOWFAST_EK100_no_opti.pkl
  AUTO_RESUME: False
  FINETUNE: False

DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]

SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product

BN:
  USE_PRECISE_STATS: True
  FREEZE: True
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0

SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 25]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: [97, 300]
  ARCH: slowfast
  MODEL_NAME: SlowFastGRU
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

TEST:
  ENABLE: True
  DATASET: EpicKitchensGRU
  BATCH_SIZE: 1
  NUM_SPATIAL_CROPS: 1

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

EPICKITCHENS:
  SINGLE_BATCH: True
  TRAIN_PLUS_VAL: False
  TRAIN_LIST: data/epic-kitchens-100-annotations/EPIC_100_train.pkl
  VAL_LIST: data/epic-kitchens-100-annotations/EPIC_100_validation.pkl
  TEST_LIST: data/epic-kitchens-100-annotations/EPIC_100_validation.pkl
  VISUAL_DATA_DIR: /rgb_frames

WANDB:
  ENABLE: True

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: results/slowfast-gru
